/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AdcPayCard {
    'acceptedCards': string[];
    'amount': number;
    /**
    * The background color of the button. The foreground will always be white. This value can be any valid CSS color, passed as a string.
    */
    'buttonColor': string;
    /**
    * What the button will show as text inside it.
    */
    'buttonLabel': string;
    'currency': string;
    /**
    * Whether the button should be disabled or not.
    */
    'isDisabled': boolean;
    'totalLabel': string;
  }
  interface AdcPayCardAttributes extends StencilHTMLAttributes {
    'acceptedCards'?: string[];
    'amount'?: number;
    /**
    * The background color of the button. The foreground will always be white. This value can be any valid CSS color, passed as a string.
    */
    'buttonColor'?: string;
    /**
    * What the button will show as text inside it.
    */
    'buttonLabel'?: string;
    'currency'?: string;
    /**
    * Whether the button should be disabled or not.
    */
    'isDisabled'?: boolean;
    'onPaymentError'?: (event: CustomEvent) => void;
    'onPaymentSuccess'?: (event: CustomEvent) => void;
    'totalLabel'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AdcPayCard': Components.AdcPayCard;
  }

  interface StencilIntrinsicElements {
    'adc-pay-card': Components.AdcPayCardAttributes;
  }


  interface HTMLAdcPayCardElement extends Components.AdcPayCard, HTMLStencilElement {}
  var HTMLAdcPayCardElement: {
    prototype: HTMLAdcPayCardElement;
    new (): HTMLAdcPayCardElement;
  };

  interface HTMLElementTagNameMap {
    'adc-pay-card': HTMLAdcPayCardElement
  }

  interface ElementTagNameMap {
    'adc-pay-card': HTMLAdcPayCardElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
