/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AdcPayCard {
    /**
    * An array of accepted card types. If omitted, all possible card types will be accepted. Possible values depend on the browser; Chrome currently accepts: amex, diners, discover, jcb, mastercard, unionpay, mir, and visa
    */
    'acceptedCards': string[];
    /**
    * Total amount to pay. Defaults to 0.
    */
    'amount': number;
    /**
    * The background color of the button. The foreground will always be white. This value can be any valid CSS color, passed as a string. Defaults to "#999999".
    */
    'buttonColor': string;
    /**
    * What the button will show as text inside it. Defaults to "Pay with card".
    */
    'buttonLabel': string;
    /**
    * Currency for the total amount. Defaults to "USD".
    */
    'currency': string;
    /**
    * Whether the button should be disabled or not. Defaults to false.
    */
    'isDisabled': boolean;
    /**
    * Label to show as description next to the amount to pay. Defaults to "Total to pay"
    */
    'totalLabel': string;
  }
  interface AdcPayCardAttributes extends StencilHTMLAttributes {
    /**
    * An array of accepted card types. If omitted, all possible card types will be accepted. Possible values depend on the browser; Chrome currently accepts: amex, diners, discover, jcb, mastercard, unionpay, mir, and visa
    */
    'acceptedCards'?: string[];
    /**
    * Total amount to pay. Defaults to 0.
    */
    'amount'?: number;
    /**
    * The background color of the button. The foreground will always be white. This value can be any valid CSS color, passed as a string. Defaults to "#999999".
    */
    'buttonColor'?: string;
    /**
    * What the button will show as text inside it. Defaults to "Pay with card".
    */
    'buttonLabel'?: string;
    /**
    * Currency for the total amount. Defaults to "USD".
    */
    'currency'?: string;
    /**
    * Whether the button should be disabled or not. Defaults to false.
    */
    'isDisabled'?: boolean;
    /**
    * Emmited when the process is not completed, typically because of the user cancelling it.
    */
    'onPaymentError'?: (event: CustomEvent) => void;
    /**
    * Emmited when the user correctly enters their payment details in the browser form.
    */
    'onPaymentSuccess'?: (event: CustomEvent) => void;
    /**
    * Label to show as description next to the amount to pay. Defaults to "Total to pay"
    */
    'totalLabel'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AdcPayCard': Components.AdcPayCard;
  }

  interface StencilIntrinsicElements {
    'adc-pay-card': Components.AdcPayCardAttributes;
  }


  interface HTMLAdcPayCardElement extends Components.AdcPayCard, HTMLStencilElement {}
  var HTMLAdcPayCardElement: {
    prototype: HTMLAdcPayCardElement;
    new (): HTMLAdcPayCardElement;
  };

  interface HTMLElementTagNameMap {
    'adc-pay-card': HTMLAdcPayCardElement
  }

  interface ElementTagNameMap {
    'adc-pay-card': HTMLAdcPayCardElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
